server:
  port: 9400
spring:
  application:
    name: atlas-monitor
  cloud:
    nacos:
      discovery:
        server-addr: 10.0.8.138:8848
        username: nacos
        password: nacos
  data:
    redis:
      host: 10.0.8.138
      port: 6379
      password: bubua12
  boot:
    admin:
      context-path: /admin
