server:
  port: 9200
spring:
  application:
    name: atlas-system
  cloud:
    nacos:
      discovery:
        server-addr: ${ATLAS_NACOS_HOST:127.0.0.1}
        username: ${ATLAS_NACOS_USERNAME:nacos}
        password: ${ATLAS_NACOS_PASSWORD:nacos}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${ATLAS_MYSQL_URL:jdbc:mysql://127.0.0.1:3306/atlas}
    username: ${ATLAS_MYSQL_USERNAME:root}
    password: ${ATLAS_MYSQL_PASSWORD:bubua12}
  data:
    redis:
      host: ${ATLAS_REDIS_HOST:127.0.0.1}
      port: ${ATLAS_REDIS_PORT:6379}
      password: ${ATLAS_REDIS_PASSWORD:bubua12}
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
