server:
  port: 9100
spring:
  application:
    name: atlas-auth
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.138:8848
        username: nacos
        password: nacos
  data:
    redis:
      host: 192.168.31.138
      port: 6379
      password: bubua12
atlas:
  jwt:
    secret: atlas-jwt-secret-key-please-change-in-production-at-least-256-bits
    expiration: 7200
