server:
  port: 9100
spring:
  application:
    name: atlas-auth
  cloud:
    nacos:
      discovery:
        server-addr: ${ATLAS_NACOS_HOST:127.0.0.1}
        username: ${ATLAS_NACOS_USERNAME:nacos}
        password: ${ATLAS_NACOS_PASSWORD:nacos}
  data:
    redis:
      host: ${ATLAS_REDIS_HOST:127.0.0.1}
      port: ${ATLAS_REDIS_PORT:6379}
      password: ${ATLAS_REDIS_PASSWORD:bubua12}
atlas:
  wecom:
    corp-id: ww0abbbd110a1aa774
    agent-id: 1000002
    secret: hjf3RLF_tsS31OQzvd8AA-XRWJF1xylCIlZw4kIyojM
    redirect-uri: https://atlas.bubua12.com/login
