server:
  port: 9300
spring:
  application:
    name: atlas-infra
  cloud:
    nacos:
      discovery:
        server-addr: ${ATLAS_NACOS_HOST:127.0.0.1}
        username: ${ATLAS_NACOS_USERNAME:nacos}
        password: ${ATLAS_NACOS_PASSWORD:nacos}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${ATLAS_MYSQL_URL:jdbc:mysql://127.0.0.1:3306/atlas}
    username: ${ATLAS_MYSQL_USERNAME:root}
    password: ${ATLAS_MYSQL_PASSWORD:bubua12}
  data:
    redis:
      host: ${ATLAS_REDIS_HOST:127.0.0.1}
      port: ${ATLAS_REDIS_PORT:6379}
      password: ${ATLAS_REDIS_PASSWORD:bubua12}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
atlas:
  file:
    upload-path: /data/atlas/upload
