management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}